services:
  postgres:
    image: postgres:16-alpine
    container_name: genericrx_postgres
    restart: always
    environment:
      POSTGRES_USER: genericrx
      POSTGRES_PASSWORD: genericrx_secret
      POSTGRES_DB: genericrx_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0
    container_name: genericrx_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: genericrx
      MONGO_INITDB_ROOT_PASSWORD: genericrx_secret
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: genericrx_backend
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: genericrx
      POSTGRES_PASSWORD: genericrx_secret
      POSTGRES_DB: genericrx_db
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: genericrx
      MONGO_PASSWORD: genericrx_secret
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: genericrx_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
  mongo_data: